#coding=gbk
new_crawlers="//button/span[text()='新建任务']"
crawlers_type="//*[@class='radio-line']/label[3]"
determine="//*[@class='form-buttons']/button[2]"
crawlers_name="//*[@class='el-input']/input"
mp="//*[@placeholder='请选择融合号']"
select_mp="/html/body/div[2]/div[1]/div[1]/ul/li/span"

add_mp="//*[@class='question']"
mp_name="//*[@for='mpName']//following-sibling::*/div[1]/input"
mp_type="//*[@for='type']//following-sibling::*/div[1]"
mp_type1="//span[text()='新闻媒体'] "
sheng="//*[@placeholder='省']"
sheng1="//span[text()='北京'] "
shi="//*[@placeholder='市']"
shi1="/html/body/div[6]/div[1]/div[1]/ul/li/span "
sure="//*[@role='dialog']/div[3]/div/button[2]"
add_lanmu="//span[contains(text(),'添加栏目')] "
input_lanmu="//label[contains(text(),'栏目名称')]//following-sibling::*/div[1]/input"
next_step="//span[contains(text(),'下一步')]"
address="//*[@class='el-input__inner']"
filished="//*[@class='step-buttons']/button[2]"